name: Build Executables

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            build-name: linux-64bit
          - os: ubuntu-latest
            arch: x86
            build-name: linux-32bit
          - os: ubuntu-latest
            arch: arm64
            build-name: linux-arm64
          - os: windows-latest
            arch: x64
            build-name: windows-64bit
          - os: windows-latest
            arch: x86
            build-name: windows-32bit
          - os: windows-latest
            arch: arm64
            build-name: windows-arm64


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install PyInstaller and dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller main.py --add-data=Data:Data
        working-directory: ./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: dist/main/*
